config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resource :messages
  resources :users
  resources :sessions
  resources :answers

  get 'sessions/new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'profile', to: 'users#show', as: 'profile'

  root to: 'home#index'
get '/about' => 'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
belongs_to :user
  def gravatar

end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :answers

  def gravatar

  end
  def self.search(search)
    where("body LIKE ?", "%#{search}%")
  end

  end

app/models/subject.rb
class Subject < ApplicationRecord
has_many :chatrooms
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :questions
  has_many :answers


  validates_uniqueness_of :email, :username

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authorize, only: [:create]
  def create
    question = Question.find(params[:answer][:question_id])
    Answer.create(answer_params)
    question.answers.create(answer_params)
    redirect_to question
  end

  private

  def answer_params
    params.require(:answer).permit(:username, :user_id, :email, :body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.last(10)
  end

  def about
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

skip_before_action :verify_authenticity_token
  def show
    @messages = Message.all
  end
  def create
    @message = Message.create!(message_params)
    PrivatePub.publish_to("/messages/new", message: @message)
    redirect_to messages_url
  end

private
  def message_params
    params.require(:message).permit(:content )
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authorize, only: [:create]
  def show
    @question = Question.find(params[:id])
@question_user = User.find(@question.user_id)
    @answers = @question.answers.order(created_at: :desc)
  end

  def create
    Question.create(question_params)
    redirect_to root_path
  end

  def index
    @questions = Question.all
    if params[:search]
      @questions = Question.search(params[:search]).order(created_at: :desc)
    else
      @questions = Question.all.order(created_at: :desc)
    end
  end

  private

  def question_params
    params.require(:question).permit(:user_id,:email,:username, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
  def show
    @user = User.find(current_user)
    @question_count = Question.count_by_sql("select count(*) from questions where user_id =#{current_user.id}")

    @question_recent = Question.find_by_sql("select* from questions where user_id = #{current_user.id}")
    end
  private
  def user_params
    params.require(:user).permit( :username ,:email, :password, :password_confirmation)
  end
  def index

  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expertchat_helper.rb
module ExpertchatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar-inverse navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Neumont Heap</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href='/about'>About</a></li>
        <li><a href="<%=questions_url %>">More Questions </a></li>
        <li>
          <button type="button" class="btn btn-primary btn-lg question-btn" data-toggle="modal" data-target="#new-question-modal">
         Ask Something
        </button>
        </li>
        <% if current_user %>
            <li class ="mavbar-right"> <a href="<%= profile_path %>"> Logged in as <%= current_user.username %>.</a></li>

            <li class="navbar-right user-logout">  <%= link_to "Log Out", logout_path %> </li>
          <% else %>
              <li class="navbar-right user-signup"> <%= link_to "Sign Up", signup_path %> </li>
              <li class='navbar-right user-login'> <%= link_to "Log In", login_path %> </li>
          <% end %>


      </ul>
    </div>
  </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/home/_new-answer-form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Answer</h4>
      </div>
      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
          <input type="hidden" name="answer[question_id]" value="<%= @question.id %>" />
          <input type="hidden" name="answer[email]" class="form-control" id="inputEmail" value="<%=	 current_user.email unless current_user == nil  %>" >
          <input type="hidden" name="answer[username]" class="form-control" id="inputUsername" value="<%=	 current_user.username unless current_user == nil %>">
          <input type="hidden" name="answer[user_id]" class="form-control" id="inputUser_id" value="<%=	 current_user.id unless current_user == nil %>">
          <div class="modal-body">
            <div class="form-group">
            <div class="form-group">
              <label for="inputAnswer" class="col-sm-2 control-label">Answer</label>
              <div class="col-sm-10">
                <textarea class="form-control" name="answer[body]" id="inputAnswer" placeholder="What is your answer?" required></textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/home/_new-question-form.erb
<div class="modal fade" id="new-question-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Question</h4>
      </div>
      <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>
          <div class="modal-body">
            <input type="hidden" name="question[username]" class="form-control" id="inputUsername" value="<%=	 current_user.username unless current_user == nil %>">
            <input type="hidden" name="question[user_id]" class="form-control" id="inputUser_id" value="<%=	 current_user.id unless current_user == nil %>">

            <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
              <div class="col-sm-10">
                <textarea class="form-control" name="question[body]" id="inputQuestion" placeholder="What would you like to know" required></textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default btn-close" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
      <% end %>
    </div>
  </div>
</div>


app/views/home/about.html.erb
<h1>About Us</h1>
<div class="container">
  <div>
    <p>
      The Neumont Heap is a website developed and designed by BS of Information Systems student,
      Austin Harmon. It is currently under his ownership and care and still in the process of continual development.


    </p>


  </div>



</div>

app/views/home/index.html.erb
<h1>Welcome to the Neumont Heap</h1>
<div class="container">
  <p>
    We're still in development, but feel free to look around

  </p>
</div>
  <div class="container">
    <% @questions.each do |q| %>
    <div class="media">
      <div class="lead well">
        <div class="media-left media-top">
      <img class="media-object" src= "<%= q.gravatar %>" >

        <div class="media-body">
          <h4 class="media-heading"><%= q.username%> asked:</h4>
          <div><%=time_ago_in_words q.created_at %> ago</div>
          <%= q.body%>
        </div>
      </div>
      </div>
        <%= link_to'View Answers',question_url(q) %>
    <%end%>
  </div>
  </div>

app/views/messages/_message.html.erb
<li>
  <span class="created_at"><%= message.created_at.strftime("%H:%M") %></span>
  <%= message.content %>
</li>

app/views/messages/create.js.erb
<% publish_to "/messages/new" do %>
$("#chat").append("<%= j render(@message) %>");
<% end %>

app/views/messages/show.html.erb
<h1>Chat</h1>

<ul id="chat">
  <%= render @messages %>
</ul>

<%= form_for Message.new, authentixity_token: true ,remote: true do |f| %>
    <%= f.text_field :content %>
    <%= f.submit "Send" %>
<% end %>

<%= subscribe_to "/messages/new" %>

app/views/questions/index.html.erb
<% @questions.each do |q| %>
    <div class="media">
      <div class="lead well">
        <div class="media-left media-top">
          <img class="media-object" src= "<%= q.gravatar %>" >

          <div class="media-body">
            <h4 class="media-heading"><%= q.username%> asked:</h4>
            <div><%=time_ago_in_words q.created_at %> ago</div>
            <%= q.body%>
          </div>
        </div>
      </div>
      <%= link_to'View Answers',question_url(q) %>
    </div>
<%end%>

app/views/questions/show.html.erb
<div class="container">
  <div class="lead well">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="<%= @question.gravatar %>">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= @question.username %> asked:</h4>
        <%= @question.body %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <div>
        <button type="button" class="btn btn-success btn-sm"  data-toggle="modal" data-target="#new-answer-modal">Submit new answer></button>
      </div>

      <%= render 'home/new-answer-form' %>

      <% @answers.each do |answer| %>
          <div class="media">
            <div class="media-left">
              <a href="#">
                <img class="media-object" src="<%= answer.gravatar %>">
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= answer.username %> answered:</h4>
              <div><%= time_ago_in_words answer.created_at %> ago</div>
              <%= answer.body %>
            </div>
          </div>
      <% end %>


    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="containe user-newr"> <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
      <br class="field">
        <%= f.label :username%> </br>
        <%= f.text_field :username %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions signup-btn"><%= f.submit "Sign Up" %></div>
<% end %>
</div>

app/views/users/show.html.erb
<h1 class="profile"><%= @user.username%>'s Profile</h1>
<div class="container user-prof ">
  <div>
    <ul>
      <li>
        Current Email  <%= @user.email %>
      </li>
      <li>Current Username <%=	@user.username %></li>
      <li>
        Questions Asked <%=	@question_count  %>

      </li>

    </ul>
  </div>
  <% @question_recent.each do |q| %>
      <div class="media">
        <div class="lead well">
          <div class="media-left media-top">
            <img class="media-object" src= <%= q.gravatar %> >

                <div class="media-body">
            <h4 class="media-heading"><%= q.username%> asked:</h4>
            <div><%=time_ago_in_words q.created_at %> ago</div>
            <%= q.body%>
          </div>
        </div>
      </div>
        <div><%= link_to'View Answers',question_url(q) %> 
  </div>
  <%end%>
  </div>
</div>