config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resource :messages
  resources :users
  resources :sessions
  resources :answers

  get 'sessions/new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'profile', to: 'users#show', as: 'profile'

  root to: 'home#index'
get '/about' => 'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
belongs_to :user
  def gravatar

end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :answers

  def gravatar

  end
  def self.search(search)
    where("body LIKE ?", "%#{search}%")
  end

  end

app/models/subject.rb
class Subject < ApplicationRecord
has_many :chatrooms
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :questions
  has_many :answers


  validates_uniqueness_of :email, :username

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authorize, only: [:create]
  def create
    question = Question.find(params[:answer][:question_id])
    Answer.create(answer_params)
    question.answers.create(answer_params)
    redirect_to question
  end

  private

  def answer_params
    params.require(:answer).permit(:username, :user_id, :email, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.last(10)
  end

  def about
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

skip_before_action :verify_authenticity_token
  def show
    @messages = Message.all
  end
  def create
    @message = Message.create!(message_params)
    PrivatePub.publish_to("/messages/new", message: @message)
    redirect_to messages_url
  end

private
  def message_params
    params.require(:message).permit(:content )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
  def show
    @user = User.find(current_user)
    @question_count = Question.count_by_sql("select count(*) from questions where user_id =#{current_user.id}")

    @question_recent = Question.find_by_sql("select* from questions where user_id = #{current_user.id}")
    end
  private
  def user_params
    params.require(:user).permit( :username ,:email, :password, :password_confirmation)
  end
  def index

  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expertchat_helper.rb
module ExpertchatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuHeap</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <%= render 'home/navbar'%>
  <div class="container search">
    <%= form_tag(questions_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :secharch, params[:search], placeholder: "Search Posts" %>
      <%= submit_tag "Search" %>
  <% end %>
</div>
  <%= yield %>
  <%= render 'home/new-question-form' %>
  </body>

<footer>
  <div class="container">
Neumont Heap Copyright 2017 by Austin Harmon
  </div>
</footer>
</html>